- HoradotTV.sln
- HoradotTV/HoradotTV.csproj
- HoradotTV/Resources/Constants.cs
- HoradotTV/Services/Checks/SdarotConnectionCheck.cs
- Resources/sdarot-url.txt
- SdarotAPI/Exceptions/DriverNotInitialized.cs
- SdarotAPI/Exceptions/SdarotBlockedException.cs
- SdarotAPI/Model/EpisodeInformation.cs
- SdarotAPI/Model/SeasonInformation.cs
- SdarotAPI/Model/SeriesInformation.cs
- SdarotAPI/Resources/Constants.cs
- SdarotAPI/SdarotAPI.cs
- SdarotAPI/SdarotAPI.csproj
- SdarotAPITest/ApiUnitTest.cs
- SdarotAPITest/SdarotAPITest.csproj
- SdarotAPITest/Usings.cs
- Added SdarotAPI project.
- Added Series, Season, and Episode models.
- Added data scraping from the website. (resolves #3)
- Added custom exceptions (DriverNotInitializedException & SdarotBlockException).
- Domain is retrieved dynamically. (resolves #4)
- Added testing project.
> Retrieving data from the website about series, seasons and episodes

- HoradotTV/Services/Checks/ChromeDownloadCheck.cs
- HoradotTV/Services/Checks/ChromeDriverCheck.cs
- HoradotTV/Services/Checks/SdarotConnectionCheck.cs
- HoradotTV/Services/ChromeDriverInstaller.cs
- SdarotAPI/Extensions/HttpClientExtensions.cs
- SdarotAPI/Extensions/StreamExtensions.cs
- SdarotAPI/Model/EpisodeInformation.cs
- SdarotAPI/Model/EpisodeMediaDetails.cs
- SdarotAPI/Model/SeasonInformation.cs
- SdarotAPI/Resources/Constants.cs
- SdarotAPI/SdarotAPI.csproj
- SdarotAPI/SdarotDriver.cs
- SdarotAPI/SdarotHelper.cs
- SdarotAPITest/ApiUnitTest.cs
- Added wait for the episode to load (including progress) (resolves #10)
- Added download episode (including progress) (resolves #5)
- Added more methods to retrieve episodes (resolves #9)
> Added episodes retrieving and downloading

- HoradotTV.Console/Program.cs
> Added download summarize

- HoradotTV.Console/GlobalUsings.cs
- HoradotTV.Console/Program.cs
- SdarotAPI/Exceptions/WebsiteErrors/Error2Exception.cs
- SdarotAPI/Exceptions/WebsiteErrors/WebsiteErrorException.cs
- SdarotAPI/GlobalUsings.cs
- SdarotAPI/Resources/Constants.cs
- SdarotAPI/SdarotDriver.cs
- resolves #14 
- resolves #37
> Added website's Error2 handling

- SdarotAPI/Resources/Constants.cs
- SdarotAPI/SdarotDriver.cs
> Added API login with webdriver

- HoradotTV.Console/Program.cs
> Added console app website login

- SdarotAPI/Resources/Constants.cs
- SdarotAPI/SdarotAPI.csproj
- SdarotAPI/SdarotDriver.cs
- SdarotAPI/SdarotHelper.cs
> Fixed driver's user agent

- HoradotTV.Console/Constants.cs
- HoradotTV.Console/Program.cs
> Added version print

- HoradotTV.Console/Constants.cs
- HoradotTV.Console/Program.cs
- SdarotAPI/SdarotDriver.cs
> Change return values to IEnumerables

- SdarotAPI/Exceptions/WebsiteErrors/ElementNotFoundException.cs
- SdarotAPI/Exceptions/WebsiteErrors/Error2Exception.cs
- SdarotAPI/SdarotDriver.cs
> Added ElementNotFoundException

- SdarotAPI/GlobalUsings.cs
- SdarotAPI/Resources/Constants.cs
- SdarotAPI/SdarotDriver.cs
- SdarotAPITest/ApiUnitTest.cs
> Change episodes retrieving to ajax calls

- HoradotTV.Console/Program.cs
> Added download completed message

- HoradotTV.Console/Program.cs
- SdarotAPI/Extensions/HttpClientExtensions.cs
- SdarotAPI/Extensions/StreamExtensions.cs
- SdarotAPI/SdarotDriver.cs
- SdarotAPI/Services/ChromeDriverHelper.cs
- SdarotAPITest/ApiUnitTest.cs
> Changed series search to get requests

- HoradotTV.Console/IOHelpers.cs
- HoradotTV.Console/Program.cs
> Added timestamps to download

- SdarotAPI/SdarotDriver.cs
- SdarotAPITest/ApiUnitTest.cs
> Changed seasons retrieving to normal GET requests

- SdarotAPI/Exceptions/SdarotBlockedException.cs
- SdarotAPI/SdarotDriver.cs
> Changed connection check to normal GET request

- SdarotAPI/Exceptions/ChromeIsNotInstalledException.cs
- SdarotAPI/SdarotDriver.cs
- SdarotAPI/Services/ChromeDriverHelper.cs
> Added driver checks

- HoradotTV.Console/GlobalUsings.cs
- HoradotTV.Console/Program.cs
- SdarotAPI/Exceptions/ChromeIsNotInstalledException.cs
- SdarotAPI/Exceptions/SdarotBlockedException.cs
> Added console messages on checks errors

- HoradotTV.Console/App.config
- HoradotTV.Console/AppSettings.cs
- HoradotTV.Console/GlobalUsings.cs
- HoradotTV.Console/Program.cs
> Saving last download location

- HoradotTV.Console/AppSettings.cs
- HoradotTV.Console/Program.cs
> Saving credentials

- HoradotTV.Console/AppSettings.cs
- HoradotTV.Console/Program.cs
> Skipping existed episodes

- HoradotTV.Console/Constants.cs
- HoradotTV.Console/IOHelpers.cs
- HoradotTV.Console/Program.cs
- SdarotAPI/GlobalUsings.cs
- SdarotAPI/Models/EpisodeInformation.cs
- SdarotAPI/Models/SeasonInformation.cs
- SdarotAPI/Models/SeriesInformation.cs
> Added failed episodes menu

- HoradotTV.Console/AppSettings.cs
- HoradotTV.Console/Constants.cs
- HoradotTV.Console/GlobalUsings.cs
- HoradotTV.Console/IOHelper.cs
- HoradotTV.Console/Program.cs
- SdarotAPI/Models/EpisodeInformation.cs
- SdarotAPI/Models/SeasonInformation.cs
- SdarotAPI/SdarotDriver.cs
> Added download from file option

- HoradotAPI/GlobalUsings.cs
- HoradotAPI/HoradotAPI.csproj
- HoradotAPI/HoradotService.cs
- HoradotAPI/Interfaces/BaseContentProvider.cs
- HoradotAPI/Interfaces/BaseShowProvider.cs
- HoradotAPI/Models/MovieInformation.cs
- HoradotAPI/Providers/SdarotTV/SdarotTVMediaDetails.cs
- HoradotAPI/Providers/SdarotTV/SdarotTVService.cs
- HoradotAPI/Providers/SratimTV/SratimTVMediaDetails.cs
- HoradotAPI/Providers/SratimTV/SratimTVMovieInformation.cs
- HoradotAPI/Providers/SratimTV/SratimTVSearchResult.cs
- HoradotAPI/Providers/SratimTV/SratimTVService.cs
- HoradotTV.Console/Constants.cs
- HoradotTV.Console/Program.cs
- HoradotTV.sln.DotSettings
- README.md
> SratimTV support and parallelism
